<template>
  <div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
  </div>
</template>

<script>
export default {
  name: 'Home',
  data() {
    return {}
  }
}
</script>

<style scoped></style>
